// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cosCpp
NumericMatrix cosCpp(NumericMatrix Xr);
RcppExport SEXP _hdpx_cosCpp(SEXP XrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Xr(XrSEXP);
    rcpp_result_gen = Rcpp::wrap(cosCpp(Xr));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP hdpMultinomial_iterate(SEXP, SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_hdpx_cosCpp", (DL_FUNC) &_hdpx_cosCpp, 1},
    {"hdpMultinomial_iterate", (DL_FUNC) &hdpMultinomial_iterate, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_hdpx(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
