# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cosCpp <- function(Xr) {
    .Call('_hdpx_cosCpp', PACKAGE = 'hdpx', Xr)
}

test_asan_overflow <- function() {
    invisible(.Call('_hdpx_test_asan_overflow', PACKAGE = 'hdpx'))
}

test_asan_use_after_free <- function() {
    invisible(.Call('_hdpx_test_asan_use_after_free', PACKAGE = 'hdpx'))
}

